"""Додав до моделі товарів посилання на картинку

Revision ID: 7782e4a16445
Revises: c0e36402ae26
Create Date: 2026-09-17 14:31:05.596810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7782e4a16445'
down_revision: Union[str, Sequence[str], None] = 'c0e36402ae26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img_url')
    # ### end Alembic commands ###
